// <auto-generated />
namespace bikeStoreDb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class drop_shipped_date : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(drop_shipped_date));
        
        string IMigrationMetadata.Id
        {
            get { return "202310081238500_drop_shipped_date"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
